[project]
name = "yt-downloader"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
requires-python = ">=3.11"
dependencies = [
    "flask>=2.3.0",
    "yt-dlp>=2023.7.6",
    "werkzeug>=2.3.0",
    "ffmpeg-python>=0.2.0",
]
